#rccities configuration
    #chunk per player
    chunkperplayer: 4


# database configuration
database:
    # valid types are:
    # MySQL
    # SQLite
    type: 'MySQL'
    # the name of the database
    database: 'minecraft'
    # username of the database
    username: 'root'
    # password of the username
    password: 'admin'
    # hostname and port of the database
    url: 'localhost:3306'
    # table prefix
    prefix: 'rccities_'