# database configuration
database:
    # valid types are:
    # MySQL
    # SQLite
    type: 'MySQL'
    # the name of the database
    database: 'minecraft'
    # username of the database
    username: 'root'
    # password of the username
    password: 'admin'
    # hostname and port of the database
    url: 'localhost:3306'
    # table prefix
    prefix: 'rccities_'

# rccities configuration
rccities:
    # chunk per player
    chunksPerPlayer: 4
    # coins per claim
    claimPrice: 1000.0
    # coin per new chunk
    chunkPrice: 5000.0
    # coins per /plot show
    markPrice: 60.0
    # town spawn warmup in seconds
    townspawnWarmup: 2