main: de.raidcraft.rccities.RCCitiesPlugin
name: RCCities
version: ${project.version}#${BUILDS_ALL_TIME}
description: Provides player towns.
author: Strasse36
website: http://www.raid-craft.de
depend: [RaidCraft-API, RCConversations]
database: true

permissions:
   rccities.admin:
     children:
       rccities.create: true
   rccities.player:
     children:
       rccities.plot.take: true
       rccities.plot.give: true
       rccities.plot.claim: true
       rccities.plot.flag: true
       rccities.plot.info: true
       rccities.resident.info: true
       rccities.town.info: true
       rccities.town.list: true
       rccities.town.leave: true
       rccities.town.kick: true