main: de.raidcraft.rccities.RCCitiesPlugin
name: RCCities
version: ${project.version}#${BUILDS_ALL_TIME}
description: Provides player towns.
author: Strasse36
website: http://www.raid-craft.de
depend: [RaidCraft-API]
database: true

permissions:
   rccities.admin:
     children:
       rccities.create: true
   rccities.player:
     children:
       rccities.leave: true

